using Hassann_Khala.Application.DTOs.Reports;
using Hassann_Khala.Application.Interfaces.IServices;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Hassann_Khala.Application.Services
{
    public class PdfService : IPdfService
    {
        public byte[] GenerateMovementDetailsPdf(MovementDetailsDto report)
        {
            var doc = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(20);
                    page.Size(PageSizes.A4);
                    page.PageColor(Colors.White);

                    page.Header().Row(row =>
                    {
                        row.RelativeColumn().Text("Movement Details Report").FontSize(20).Bold();
                        row.ConstantColumn(200).Text($"Date: {DateTime.UtcNow:yyyy-MM-dd}").AlignRight();
                    });

                    page.Content().Column(col =>
                    {
                        col.Spacing(10);

                        col.Item().Text($"Filters: Client={report.Filter.ClientId}, Section={report.Filter.SectionId}, Product={report.Filter.ProductId}").FontSize(10);

                        foreach (var g in report.Groups)
                        {
                            col.Item().Text(g.GroupName).FontSize(14).Bold();
                            col.Item().Table(table =>
                            {
                                table.ColumnsDefinition(columns =>
                                {
                                    columns.ConstantColumn(40);
                                    columns.RelativeColumn();
                                    columns.RelativeColumn();
                                    columns.RelativeColumn();
                                    columns.RelativeColumn();
                                });

                                table.Header(header =>
                                {
                                    header.Cell().Element(CellStyle).Text("#");
                                    header.Cell().Element(CellStyle).Text("Product");
                                    header.Cell().Element(CellStyle).Text("Type");
                                    header.Cell().Element(CellStyle).Text("Qty");
                                    header.Cell().Element(CellStyle).Text("Date");
                                });

                                int idx = 1;
                                foreach (var m in g.Movements)
                                {
                                    table.Cell().Element(CellStyle).Text(idx++.ToString());
                                    table.Cell().Element(CellStyle).Text(m.ProductName);
                                    table.Cell().Element(CellStyle).Text(m.MovementType);
                                    table.Cell().Element(CellStyle).Text(m.Quantity.ToString());
                                    table.Cell().Element(CellStyle).Text(m.Date.ToString("yyyy-MM-dd"));
                                }

                                table.Footer(footer =>
                                {
                                    footer.Cell().ColumnSpan(2).Element(CellStyle).Text("Totals");
                                    footer.Cell().Element(CellStyle).Text(string.Empty);
                                    footer.Cell().Element(CellStyle).Text(g.Net.ToString());
                                    footer.Cell().Element(CellStyle).Text(string.Empty);
                                });

                                static IContainer CellStyle(IContainer c)
                                {
                                    return c.Padding(5).Border(1).BorderColor(Colors.Grey.Lighten3);
                                }
                            });
                        }
                    });

                    page.Footer().AlignCenter().Text(x =>
                    {
                        x.Span("Generated by Hassann Khala System").FontSize(10);
                    });
                });
            });

            var bytes = doc.GeneratePdf();
            return bytes;
        }
    }
}
